apiVersion: v1
kind: ReplicationController
metadata:
name: javawebapprc
spec:
replicas: 2
selector:
app: javawebapp
 namespace: javawebappspace
template:
metadata:
name: javawebapppod
labels:
app: javawebapp
 namespace: javawebappspace
spec:
containers:
- name: javawebappcontainer
image: agunuworld/java-web-app:8
ports:
- containerPort: 80
    
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  name: javawebappservice                             #service name varies it can be any name
  namespace: javawebappspace
spec:
  type: NodePort                                             #type of service and we have two types of services NodePortip and Notepod
  selector:
     app: javawebapp                                     #this selector helps to identify the label created in the pod
  ports:
  - port: 80                                                  #default
    targetPort: 8080    #target application of the pod app
    nodePort: 30000

