apiVersion: v1
kind: ReplicationController
metadata:
  labels:
     app: javawebapp
  namespace: javawebappspace
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
       containers:
       - name: javawebappcontainer
        image: agunuworld/java-web-app:8
        ports:
        - containerPort: 8080
        
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  name: javawebappservice                             #service name varies it can be any name
spec:
  type: NodePort                                             #type of service and we have two types of services NodePortip and Notepod
  selector:
     app: javawebapp                                     #this selector helps to identify the label created in the pod
     namespace: javawebappspace
  ports:
  - port: 80                                                  #default
    targetPort: 8080    #target application of the pod app
    nodePort: 30002

