---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: javawebappjacocoworld
  namespace: jacocoworld
spec:
  replicas: 1
  template:
    metadata:
      labels:
         app: javawebappjacocoworld
    spec:
      containers:
      - image: agunuworld/java-web-app
        name: javawebapp
        ports:
        - name: javawebapp
          containerPort: 8080  
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: javawebapp
  namespace: jacocworld
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      NodePort: 33332
  selector:
     app: javawebappjacocoworld
